name: dashboard
channels:
  - ejolly
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - streamlit
  - cython
  - scikit-learn
  - pymer4=0.9.2
  - plotly
  - patsy
  - tqdm
  - polars
  - joblib
  - c-compiler
  - cxx-compiler
  - pip
  - pip:
    - uuid
    - inmoose 
